language: node_js
node_js:
  - "lts/*"

install:
  - npm i -g swagger2openapi

script:
  - swagger2openapi src/main/resources/swagger/ga4gh-tool-discovery.yaml -o src/main/resources/swagger/openapi.yaml
